[tool.black]
line-length = 126
include = '\.pyi?$'
target_version = ['py310']
exclude = '''(
  venv
)
'''

[tool.isort]
profile = "black"
py_version = 310
skip_gitignore = true
line_length = 126
use_parentheses = true
force_alphabetical_sort_within_sections = true