"""initial

Revision ID: 5b5b1f983f03
Revises:
Create Date: 2023-06-03 22:27:41.127641

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5b5b1f983f03"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "area",
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("area_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("area_id", name=op.f("pk__area")),
    )
    op.create_index(op.f("ix__area__area_number"), "area", ["area_number"], unique=True)
    op.create_table(
        "courier_type",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rating_coefficient", sa.Integer(), nullable=False),
        sa.Column("salary_coefficient", sa.Integer(), nullable=False),
        sa.Column("max_area", sa.Integer(), nullable=False),
        sa.Column("max_weight_orders", sa.Integer(), nullable=False),
        sa.Column("max_orders_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__courier_type")),
    )
    op.create_table(
        "courier",
        sa.Column("courier_id", sa.Integer(), nullable=False),
        sa.Column("courier_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["courier_type"], ["courier_type.id"], name=op.f("fk__courier__courier_type__courier_type")),
        sa.PrimaryKeyConstraint("courier_id", name=op.f("pk__courier")),
    )
    op.create_table(
        "courier_area",
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("courier_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["area_id"], ["area.area_id"], name=op.f("fk__courier_area__area_id__area")),
        sa.ForeignKeyConstraint(["courier_id"], ["courier.courier_id"], name=op.f("fk__courier_area__courier_id__courier")),
    )
    op.create_table(
        "courier_work_time",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_at", postgresql.TIME(), nullable=False),
        sa.Column("end_at", postgresql.TIME(), nullable=False),
        sa.Column("courier_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"], ["courier.courier_id"], name=op.f("fk__courier_work_time__courier_id__courier")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__courier_work_time")),
    )
    op.create_table(
        "order",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("region", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("assigned", sa.Boolean(), nullable=True),
        sa.Column("completed_time", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("courier", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["courier"], ["courier.courier_id"], name=op.f("fk__order__courier__courier")),
        sa.ForeignKeyConstraint(["region"], ["area.area_id"], name=op.f("fk__order__region__area")),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk__order")),
    )
    op.create_table(
        "order_delivery_hour",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_at", postgresql.TIME(), nullable=False),
        sa.Column("end_at", postgresql.TIME(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["order.order_id"], name=op.f("fk__order_delivery_hour__order_id__order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__order_delivery_hour")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_delivery_hour")
    op.drop_table("order")
    op.drop_table("courier_work_time")
    op.drop_table("courier_area")
    op.drop_table("courier")
    op.drop_table("courier_type")
    op.drop_index(op.f("ix__area__area_number"), table_name="area")
    op.drop_table("area")
    # ### end Alembic commands ###
